# Site settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed   # RSS for blog
  - jekyll-sitemap

# Site information
title: "Taro Yamada – Planetary Biophysics Lab"
email: "taro@example.ac.jp"
description: "Research on planetary evolution, biophysics, and gene regulatory networks"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Navigation order (used below)
nav_order:
  - index.md
  - about.md
  - research.md
  - publications.md
  - teaching.md
  - cv.md
  - news.md
  - blog.md
  - contact.md

# Collections (for future expansion)
collections:
  posts:
    output: true
